// This file has been autogenerated from a class added in the UI designer.

using System;

using Foundation;
using AppKit;

namespace VkBot.MacApp
{
	public partial class startButton : NSButton
	{
		public startButton (IntPtr handle) : base (handle)
		{
		}
	}
}
