// This file has been autogenerated from a class added in the UI designer.

using System;

using Foundation;
using AppKit;

namespace VkBot.MacApp
{
	public partial class BrowserViewController : NSViewController
	{
		public BrowserViewController (IntPtr handle) : base (handle)
		{
		}

		public BrowserViewController() : base()
		{
			
		}
	}
}
